app:
  name: yanal
  imports:
    - kivymd.app: MDApp
    - kivymd.uix.button: MDFloatingActionButtonSpeedDial
    - kivy.lang: Builder
  kv: |
    Screen:
        MDFloatingActionButtonSpeedDial:
            data: app.data
            rotation_root_button: True
  data:
    youtube: 'YouTube'
    facebook: 'Facebook'
    telegram: 'Telegram'
    google: 'Google'
  build: |
    return Builder.load_string(KV)
